// Jest Snapshot v1, https://jestjs.io/docs/snapshot-testing

exports[`handles errors with BigInt 1`] = `
"FAIL __tests__/test-1.js
  ● dummy

    expect(received).toEqual(expected) // deep equality

    Expected: 2n
    Received: 1n

      1 | test('dummy', () => {
    > 2 |   expect(1n).toEqual(2n);
        |              ^
      3 | });

      at Object.toEqual (__tests__/test-1.js:2:14)

FAIL __tests__/test-2.js
  ● dummy

    expect(received).toEqual(expected) // deep equality

    Expected: 2n
    Received: 1n

      1 | test('dummy', () => {
    > 2 |   expect(1n).toEqual(2n);
        |              ^
      3 | });

      at Object.toEqual (__tests__/test-2.js:2:14)"
`;

exports[`handles functions that close over outside variables 1`] = `
"FAIL __tests__/test-1.js
  ● dummy

    boom

      2 |
      3 | test('dummy', () => {
    > 4 |   const error = new Error('boom');
        |                 ^
      5 |
      6 |   error.someProp = () => someString;
      7 |

      at Object.<anonymous> (__tests__/test-1.js:4:17)

FAIL __tests__/test-2.js
  ● dummy

    boom

      2 |
      3 | test('dummy', () => {
    > 4 |   const error = new Error('boom');
        |                 ^
      5 |
      6 |   error.someProp = () => someString;
      7 |

      at Object.<anonymous> (__tests__/test-2.js:4:17)"
`;
